config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  get 'languages/change_language'

  
  
  get 'sing_in_by_token' => 'courses#sing_in_by_token'
  
  resources :languages do
    get 'change_language/:language' => 'languages#change_language'
  end
  
  resources :courses do
    post 'delete_enrollments' => 'enrollments#destroy_course_enrollments'
    get 'engagement_performance'
    get 'effectiveness_efficiency'
    get 'get_enrolled_weeks'
    get 'day_of_course'

    get 'engagement_performance_data' => 'dashboard#engagement_performance_data'
    get 'effectiveness_efficiency_data' => 'dashboard#effectiveness_efficiency_data'

    get 'progress_and_course_time_use' => 'dashboard#progress_and_course_time_use'
    get 'required_activities' => 'dashboard#required_activities'
  end

  resources :dashboard, only: :index do
    get 'sing_in_by_token', on: :collection
  end

  resources :notes do
  end

  get 'download_notes' => 'notes#download', :as => 'download_notes'

  get 'dashboard/effectiveness_data', :defaults => { :format => 'json' }
  get 'dashboard/activities_complete_data', :defaults => { :format => 'json' }

  resources :goals, only: [:index,:create] do
    get 'change_week',on: :collection
  end


  namespace :api, :defaults => { :format => 'json' } do
    post 'sign_up' => 'user_authentication#register_user'
    post 'auth_user' => 'user_authentication#authenticate_user'
    get 'validate_token' => 'user_authentication#validate_token'
    get 'urls' => 'url_receiver#index'
    post 'urls' => 'url_receiver#save_visited_url'

    #TODO: Create namespace for notes
    post 'create_note' => 'note#save_note'
    post 'get_note' => 'note#get_note'
    get 'notes' => 'note#notes'
    get 'courses' => 'courses#index'

    post 'get_effective_time' => 'charts#get_effective_time'

    namespace :sessions do
      post 'start', method: :start
      post 'get_current', method: :get_current
      post 'close', method: :close
    end

    namespace :user_profile do
      get 'details', method: :user_details
      post 'edit', method: :edit
      post 'destroy', method: :destroy
    end

  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/note.rb
class Note < ApplicationRecord
  before_save :set_title

  paginates_per 5

  belongs_to :user
  belongs_to :course, optional: true


  before_create :generate_token

  scope :from_user, -> (user_id) { where(user_id: user_id) }

  def self.search(search)
    if search
      where('title like ? OR body like ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  protected

  def set_title
    self.title = "No title" if self.title.blank?
  end

  def generate_token
    self.code = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Note.exists?(code: random_token)
    end
  end
end

app/controllers/api/note_controller.rb
class Api::NoteController < Api::ApiController
  before_action :authenticate_request!

  def save_visited_url

    if params[:url] and params[:active_time] and params[:start] and params[:finish]
      # new_url = VisitedUrl.new(url: params[:url], start: params[:start], finish: params[:finish], user: current_user)
      new_session = Session.new(user: current_user, start: params[:start].to_datetime, duration: params[:active_time])

      if SessionResource.build_from_url(new_session, params[:start].to_datetime, params[:finish].to_datetime, params[:active_time], params[:url])
        render json: {success: ["URL was successfully saved."]}, status: :created
      else
        render json: {errors: ["Couldn't save the URL, try again."]}, status: 404
      end
    else
      render json: {errors: ['Expecting params url, active_time, start and finish.']}, status: 500
    end
  end

  def notes
    @notes = current_user.notes

    if @notes
      render json: {notes: @notes}, status: :created
    else
      render json: {errors: ["The notes couldnt be founded"]}, status: 500
    end
  end

  def get_note
    code = params[:code]
    @note = Note.find_by_code(code)
    if @note
      render json: @note, status: :created
    else
      render json: {errors: @note.errors().to_json}, status: 500
    end
  end

  def save_note
    title = params[:title]
    course_id = params[:course_id]
    body = params[:body]

    @note = Note.new(title:title, course_id: course_id, body:body,user_id:current_user.id)

    if @note.save()
      render json: @note.to_json(only: [:title, :body, :code]), status: :created
    else
      render json: {errors: @note.errors().to_json}, status: 500
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.from_user(current_user).search(params[:search]).order(created_at: :desc).page params[:page]
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /notes/1/edit
  def edit
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def render_notes
    if params[:note_id]
      @notes = Note.find(params[:id])
    else
      @notes = Note.all.where(user_id: current_user)
    end
  end

  def download
    if params[:id] != ""
      @notes = Note.where(id: params[:id])
    else
      @notes = Note.where(user_id: current_user).order(:created_at)
    end

    html = render_to_string(:template => 'notes/render_notes.html.erb', layout: false).encode("UTF-8") 

    pdf = WickedPdf.new.pdf_from_string(html, :encoding => 'UTF-8') 
    if @notes.length == 1
      title = @notes.first.title
      send_data(pdf, 
          :filename    => "#{title}.pdf", 
          :encoding => "utf8",          
          :disposition => 'attachment')
    else
      title = 'all_notes'
      send_data(pdf,
          :filename => "#{title}.pdf",
          :encoding => "utf8",          
          :disposition => 'attachment')
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :course_id, :body)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <div class="col-md-12">
    <% if note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title, "#{I18n.t("notes.form.title")}" %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>

    <br/>

    <div class="field">
      <%= f.label :course, "#{I18n.t("notes.form.course")}" %><br />
      <%= f.collection_select :course_id, current_user.courses, :id, :full_name,  {:include_blank => "#{I18n.t("notes.form.select_a_course")}"}, {class: "form-control"} %>
    </div>

    <br/>

    <div class="field">
      <%= f.label :body, "#{I18n.t("notes.form.body")}" %>
      <%= f.text_area :body, :class => "form-control", :required => true, :data => { provider: 'summernote'} %>
    </div>

  </div>

  <div class="col-md-6">
    <%= link_to notes_path, class: "btn btn-md btn-default" do %><i class="fa fa-backward"></i><%= "#{I18n.t("notes.form.back")}" %><% end %>
  </div>
  <div class="col-md-6">
    <div class="actions pull-right">
      <%= f.submit "#{I18n.t("notes.form.save")}" , :class => "btn btn-md btn-primary" %>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'form', note: @note %>
</div>

app/views/notes/index.html.erb
<div class="col-xs-12">
  <div class="row">
    <div class="col-xs-12">
      <div class="pull-left">
        <%= page_entries_info @notes, entry_name: 'item' %>
      </div>
      <div class="pull-right">
        <%= link_to new_note_path, class: 'btn btn-primary original analytics-click-newNote', data: {toggle: "tooltip", placement: "bottom"}, title: "#{I18n.t("notes.new_note")}" do %><span class="glyphicon glyphicon-plus"></span><% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <hr>
    </div>
  </div>

  <div class="col-md-4 col-md-offset-2">
    <div class='pull-left'>
      <%= link_to download_notes_path(id: '', format: :pdf), data: {toggle: "tooltip", placement: "bottom"}, target: '_blank', class: "btn btn-default analytics-click-downloadAllNotes" do %><i class="fa fa-download"> <span><%= I18n.t('notes.download_all')%></span></i><% end %>
    </div>
  </div>

  <div class="col-md-4">
    <%= form_tag notes_path, :method => 'get', class: 'input-group'  do %>
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "#{I18n.t("notes.search_for")}" %>
    <span class="input-group-btn">
      <%= button_tag(type: "submit", class: "btn btn-info original analytics-click-searchNote") do %>
      <i class="glyphicon glyphicon-search"></i>
      <% end %>
    </span>
    <% end %>
    
  </div>

  <br/>
  <br/>
  <br/>

  <div class="col-md-8 col-md-offset-2">
    <% @notes.each do |note| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= note.id %>">
            <%= note.title.truncate(33, separator: ' ') %> <span class="note-date"><%= '-' + note.created_at.strftime("%m/%d/%Y") %> </span><span class="note-course"><%= ' - ' +  note.course.full_name.truncate(40, separator: ' ') if note.course.present? %></span>
          </a>

          <div class="pull-right">
            <% note_course_id = note.course.present? ? note.course.id : nil %>
            <%= link_to edit_note_path(note), data: {toggle: "tooltip", placement: "bottom"}, title: "#{I18n.t("notes.edit")}", class: "analytics-click-editNote", 'data-course-id': note_course_id do %><i class="fa fa-pencil"></i><% end %>
            <%= link_to download_notes_path(id: note.id, format: :pdf), data: {toggle: "tooltip", placement: "bottom"}, title: "Download note", target: '_blank', class: "analytics-click-downloadNote", 'data-course-id': note_course_id do %><i class="fa fa-download"></i><% end %>                        
            <%= link_to note, method: :delete, data: {toggle: "tooltip", placement: "bottom", confirm: "#{I18n.t("notes.are_you_sure")}"}, title: "#{I18n.t("notes.delete")}", class: "analytics-click-deleteNote", 'data-course-id': note_course_id do %><i class="fa fa-trash"></i><% end %>
          </div>
        </h4>
      </div>
      <div id="collapse<%= note.id %>" class="panel-collapse collapse in">
        <div class="panel-body">
          <%= note.body.html_safe %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="col-md-8 col-md-offset-2">
  <div class="pull-right">                              
    <%= paginate @notes, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'form', note: @note %>
</div>

app/views/notes/render_notes.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= wicked_pdf_stylesheet_link_tag "application" %>
    <!-- <%= wicked_pdf_stylesheet_link_tag "notes" %> -->
</head>
<style>
    body {
        background-color: white !important;
    }
    html {
        background-color: white !important;
    }
</style>
<body>

<div class="col-md-8 col-md-offset-2 notes-pdf">
    <% @notes.each do |note| %>
    <div class="panel panel-default notes-pdf">
      <div class="panel-heading notes-pdf">
        <h4 class="panel-title">
          <p data-toggle="collapse" data-parent="#accordion" href="#collapse<%= note.id %>">
            <%= note.title.truncate(33, separator: ' ') %> <span class="note-date"><%= '-' + note.created_at.strftime("%m/%d/%Y") %> </span><span class="note-course"><%= ' - ' +  note.course.full_name.truncate(40, separator: ' ') if note.course.present? %></span>
          </p>

        </h4>
      </div>
      <div id="collapse<%= note.id %>" class="panel-collapse collapse in">
        <div class="panel-body">
          <%= note.body.html_safe %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</body>
</html>