config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  get 'languages/change_language'

  
  
  get 'sing_in_by_token' => 'courses#sing_in_by_token'
  
  resources :languages do
    get 'change_language/:language' => 'languages#change_language'
  end
  
  resources :courses do
    post 'delete_enrollments' => 'enrollments#destroy_course_enrollments'
    get 'engagement_performance'
    get 'effectiveness_efficiency'
    get 'get_enrolled_weeks'
    get 'day_of_course'

    get 'engagement_performance_data' => 'dashboard#engagement_performance_data'
    get 'effectiveness_efficiency_data' => 'dashboard#effectiveness_efficiency_data'

    get 'progress_and_course_time_use' => 'dashboard#progress_and_course_time_use'
    get 'required_activities' => 'dashboard#required_activities'
  end

  resources :dashboard, only: :index do
    get 'sing_in_by_token', on: :collection
  end

  resources :notes do
  end

  get 'download_notes' => 'notes#download', :as => 'download_notes'

  get 'dashboard/effectiveness_data', :defaults => { :format => 'json' }
  get 'dashboard/activities_complete_data', :defaults => { :format => 'json' }

  resources :goals, only: [:index,:create] do
    get 'change_week',on: :collection
  end


  namespace :api, :defaults => { :format => 'json' } do
    post 'sign_up' => 'user_authentication#register_user'
    post 'auth_user' => 'user_authentication#authenticate_user'
    get 'validate_token' => 'user_authentication#validate_token'
    get 'urls' => 'url_receiver#index'
    post 'urls' => 'url_receiver#save_visited_url'

    #TODO: Create namespace for notes
    post 'create_note' => 'note#save_note'
    post 'get_note' => 'note#get_note'
    get 'notes' => 'note#notes'
    get 'courses' => 'courses#index'

    post 'get_effective_time' => 'charts#get_effective_time'

    namespace :sessions do
      post 'start', method: :start
      post 'get_current', method: :get_current
      post 'close', method: :close
    end

    namespace :user_profile do
      get 'details', method: :user_details
      post 'edit', method: :edit
      post 'destroy', method: :destroy
    end

  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/api/courses_controller.rb
class Api::CoursesController < Api::ApiController
  before_action :authenticate_request!

  def index
    @courses = current_user.courses.order(full_name: :asc)

    render json: {courses: @courses}, status: :ok
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, except: [:sing_in_by_token, :index]
  before_action :authenticate_user!, except: :sing_in_by_token
  before_action :process_token, only: [:sing_in_by_token]

  # CHECK
  def sing_in_by_token
    redirect_to action: "index"
  end

  # CHECK
  def index
    @courses = Course.from_user(current_user).uniq
  end

  # CHECK
  def engagement_performance
    user_enrollment = Enrollment.from_user(current_user).from_course(@course).last
    @weeks_on_course = user_enrollment.current_week
    @course_duration = @course.duration
    @temporal_options_time_use = ['Last 7 days', 'Last 30 days', 'View all'];
    @active_week = @course_duration + Course::OFF_SET < @weeks_on_course ? (@course_duration + Course::OFF_SET) : @weeks_on_course

    date_start_last_edition = user_enrollment.edition.start
    @date_enrolled = user_enrollment.date_enrolled
    @start_date = [@date_enrolled.to_datetime.beginning_of_day, date_start_last_edition].max
    @end_date = Date.today.to_datetime.end_of_day

    user_sessions = Session.from_user(current_user).from_course(@course).where(start: @start_date..@end_date).distinct

    other_students_data = ActivityDetailView.where("course_id_lms = ?", @course.id_lms).group(:student_course_state).average(:total_time_spent)

    @user_time_in_course = format_duration(SessionResource.joins(:resource).where("session_resources.session_id IN (?) AND resources.course_id = ? AND resources.category != ? ", user_sessions.map(&:id), @course, Resource::CATEGORIES[:others]).sum(:active_time))
    @completers_time_in_course = format_duration(other_students_data['completed'].to_i + other_students_data['completed_without_certificate'].to_i)
    @no_completers_time_in_course = format_duration(other_students_data['not_completed'].to_i)

    @user_study_frequency = format_duration(current_user.study_frequency(@course))
    # @completers_study_frequency = format_duration(0)
    # @no_completers_study_frequency = format_duration(0)
  end

  # CHECK
  def effectiveness_efficiency
    user_enrollment = Enrollment.from_user(current_user).from_course(@course).last
    @weeks_on_course = user_enrollment.current_week

    course_resources = Resource.from_course(@course)
    @time_required = course_resources.group(:resource_type).sum(:duration)

    @user_time_in_course =  course_resources.joins(:sessions)
                                            .where("sessions.user_id = ? AND resources.category != ? ", current_user.id, Resource::CATEGORIES[:others])
                                            .group("resources.resource_type")
                                            .sum("session_resources.active_time")

    @completers_time_in_course = ActivityDetailView.where(course_id_lms: @course.id_lms, student_course_state: 'completed')
                                                   .sum(:total_time_spent).to_int

    @completers_time = ActivityDetailView.where(course_id_lms: @course.id_lms, student_course_state: 'completed', week: @weeks_on_course)
                                          .group(:course_item_type_desc).average(:total_time_spent)

    @not_completers_time = ActivityDetailView.where(course_id_lms: @course.id_lms, student_course_state: 'not_completed', week: @weeks_on_course)
                                              .group(:course_item_type_desc).average(:total_time_spent)

    @resources = @user_time_in_course.map{ |key, value|
      {
        name: key.capitalize.pluralize,
        time_required: format_duration(@time_required[key]*60),
        time_invested: format_duration(value),
        completers_time: @completers_time[key].present? ? format_duration(@completers_time[key].to_int) : format_duration(0),
        not_completers_time: @not_completers_time[key].present? ? format_duration(@not_completers_time[key].to_int) : format_duration(0)
      }
    }
  end


  private

  def set_course
    @course = Course.find(params[:course_id])
  end

end

app/helpers/api/courses_helper.rb
module Api::CoursesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/effectiveness_efficiency.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= dashboard_selector %>
  </div>
</div>

<div class="row">
  <div id="section-container">
    <div class="col-xs-12">
      <h4 class="section-title">
        <%= I18n.t('section_titles.course_global_efficiency') %>
        <%= info_message(I18n.t('graphs.tooltips.efficiency_global')) %>                                               
      </h4>
      <hr class="section-title-underline">
    </div>

    <div class="col-xs-12" >
      <div class="chart-container well" style = "overflow-x:scroll; display:flex;" >
        <% @resources.each do |r| %>

        <div class="col-xs-6 col-lg-3" style="flex: 0 0 25%">
          <h4><%= I18n.t("graphs.resourceType.#{r[:name]}") %></h4>

          <table class="table borderless" style="border-left: 2px solid #d4e3e8;">
            <tr>
              <td><b><%= I18n.t('section_titles.time_required') %></b></td>
              <td class="kpi-text"><%= r[:time_required] %> <%= I18n.t('datetime.prompts.hours') %></td>
            </tr>
            <tr>
              <td><b><%= I18n.t('section_titles.time_invested.title') %></b></td>
              <td class="kpi-text"></td>
            </tr>
            <tr>
              <td><div class="margined-left"><%= I18n.t('section_titles.time_invested.you') %></div></td>
              <td class="kpi-text"><%= r[:time_invested] %> <%= I18n.t('datetime.prompts.hours') %></td>
            </tr>
            <tr>
              <td><div class="margined-left"><%= I18n.t('section_titles.time_invested.student_completed') %></div></td>
              <td class="kpi-text"><%= r[:completers_time] %> <%= I18n.t('datetime.prompts.hours') %></td>
            </tr>
            <tr>
              <td><div class="margined-left"><%= I18n.t('section_titles.time_invested.student_not_completed') %></div></td>
              <td class="kpi-text"><%= r[:not_completers_time] %> <%= I18n.t('datetime.prompts.hours') %></td>
            </tr>

          </table>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-xs-12">
      <span id='EE-sequence'></span>
    </div>

    <div class="col-xs-12 col-lg-4" style="margin-top:20px;">
      <div class="chart-container well">
        <h3 class="chart-title"> 
          <%= I18n.t('graphs.ee.titles.efficiency_by_activity_type') %>
          <%= info_message(I18n.t('graphs.tooltips.efficiency_act_type')) %>                                       
        </h3>        
          <span id='started-activities' class="elearn-chart"></span>
      </div>
    </div>

    <div class="col-xs-12 col-lg-8" style="margin-top:20px;">
      <div class="row">
        <div class="col-md-12">
          <div class="chart-container well">
            <h3 class="chart-title"> 
              <%= I18n.t('graphs.ee.titles.efficiency_by_day_of_week') %> 
              <%= info_message(I18n.t('graphs.tooltips.efficiency_day_week')) %>                             
            </h3>
            <span id="efficiency-by-day" class="elearn-chart"></span>
          </div>
        </div>

        <div class="col-md-12">
          <div class="chart-container well">
            <h3 class="chart-title">
               <%= I18n.t('graphs.ee.titles.efficiency_by_hour_of_day') %> 
               <%= info_message(I18n.t('graphs.tooltips.efficiency_hour_day')) %>               
            </h3>
            <span id="efficiency-by-hour" class="elearn-chart"></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/engagement_performance.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= dashboard_selector %>
  </div>
</div>

<div class="row">
  <div class="section-container">
    <div class="col-xs-12">
      <h4 class="section-title">
        <%= I18n.t('section_titles.course_global_engagement_performance') %>
        <%= info_message(I18n.t('graphs.tooltips.global_engagement_section_info')) %>
      </h4>
      <hr class="section-title-underline">
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="col-xs-12">
        <div class="row">
          <div class="chart-container well">

            <table class="table table-condensed top-kpis">
              <thead>
                <tr>
                  <th></th>
                  <th><%= I18n.t('pronouns.You') %></th>
                  <th><%= I18n.t('graphs.general_estadistic.completers') %></th>
                  <th><%= I18n.t('graphs.general_estadistic.no_completers') %></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th class="no-left-padding"><%= I18n.t('graphs.total_time_invested') %></th>
                  <td><%= @user_time_in_course %> <%= I18n.t('datetime.prompts.hours') %> </td>
                  <td><%= @completers_time_in_course %> <%= I18n.t('datetime.prompts.hours') %></td>
                  <td><%= @no_completers_time_in_course %> <%= I18n.t('datetime.prompts.hours') %></td>
                </tr>
                <tr>
                  <th class="no-left-padding"><%= I18n.t('graphs.study_frequency') %></th>
                  <td><%= @user_study_frequency %> <%= I18n.t('datetime.prompts.hours') %></td>
                  <td><%= @completers_study_frequency %> </td>
                  <td><%= @no_completers_study_frequency %> </td>
                </tr>
              </tbody>
            </table>

            <br>
            <span id="course-progress"></span>
          </div>

        </div>
      </div>
    </div>

    <div class="col-xs-12 col-lg-6">
      <div class="chart-container well">
        <div class="col-xs-6">
          <h3 class="chart-title"> 
            <%= I18n.t('graphs.time_use_over_course') %>
            <%= info_message(I18n.t('graphs.tooltips.time_use_over_course')) %>                                        
          </h3>
        </div>
        <div class="col-xs-6">
          <div class="btn-group pull-right" style="margin-top:10px;">
            <% @temporal_options_time_use.each_with_index do |lab,i| %>
              <button type="button" class="btn btn-sm btn-default time-use-btn analytics-click-courseTimeUseTemporalFilter<%= i %> <%= 'active' if i == 2 %>" data-temporal-filter="<%= ['last week', 'last month', 'all'][i] %>"><%= I18n.t("buttons.time_use_over_course.#{lab}") %></button>
            <% end %>
          </div>
        </div>
        <span id='course-time' class="elearn-chart"></span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="section-container">
    <div class="col-xs-12">
      <h4 class="section-title"><%= I18n.t('section_titles.course_details_engagemente_performance') %></h4>
      <hr class="section-title-underline">
    </div>

    <div class="col-xs-12">

      <div class="row" style="margin-bottom: 20px;">
        <div class="col-xs-12 col-sm-7">
          <span style="font-size:15px; font-family: 'Poppins';">
            <%= I18n.t('graphs.weeks_on_course') %> 
            <%= info_message(I18n.t('graphs.tooltips.weeks_on_course')) %> 
           </span>
          <div class="btn-group" style="padding-left: 20px;">
            <% (1..@course_duration + Course::OFF_SET).each do |week| %>
            <button type="button" class="btn btn-sm btn-<%= week > @course.duration ? 'danger' : 'primary'%> week-btn <%= 'active' if week == @active_week %> <%= 'disabled' if @active_week < week %> " value="<%= week %>"><%= week %></button>
            <% end %>
          </div>
          <button type="button" class="btn btn-sm btn-primary week-btn analytics-click-sessionsViewAll" value="view all" style="margin-left:10px;"><%= I18n.t('buttons.view_all') %></button>
        </div>

        <div class="col-xs-12 col-sm-5">
          <span id='EP-sequence' class="pull-right"></span>
        </div>
      </div>


      <div class="row">
        <div class="col-xs-12">
          <div class="chart-container well">
            <div class="col-xs-6">
              <h3 class="chart-title">
                <%= I18n.t('graphs.study_sessions_this_week') %>
                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="right" data-html="true" data-container="body"
                title="<b><%= I18n.t('graphs.tooltips.week_detail_info.header') %></b><br/><%= I18n.t('graphs.tooltips.week_detail_info.text') %>" >
                </i>
              </h3>
            </div>

            <span id='sessions-chart' class="elearn-chart"></span>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <span id='total-time' width="100%"></span>
        </div>

        <div class="col-xs-12 col-lg-6">
          <div class="chart-container well">
            <h3 class="chart-title"> 
              <%= I18n.t('graphs.ep.titles.your_time_use') %> 
              <%= info_message(I18n.t('graphs.tooltips.engagement_by_time_use')) %>                            
              
            </h3>
            <span id='time-use-chart' class="elearn-chart"></span>
          </div>
        </div>

        <div class="col-xs-12 col-lg-6">
          <div class="chart-container well">
            <h3 class="chart-title"> 
              <%= I18n.t('graphs.ep.titles.your_engagement_by_activities') %>
              <%= info_message(I18n.t('graphs.tooltips.engagement_by_num_act')) %>                            
            </h3>
            <span id='engagement-by-number-of-activities' class="elearn-chart"></span>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="chart-container well">
            <h3 class="chart-title"> 
              <%= I18n.t('graphs.ep.titles.your_engagement_by_activity_type') %>
              <%= info_message(I18n.t('graphs.tooltips.engagement_by_act_type')) %>              
            </h3>
            <div class="pull-right">
              <!-- <input id="comparation" type="checkbox" data-toggle="toggle" data-size="small" data-width="150" data-on="Comparations<br>enabled" data-off="Comparations<br>disabled"> -->
              <input id="comparation" type="checkbox" data-toggle="toggle" data-size="small" data-width="150" data-on=<%= I18n.t("buttons.engagement_by_activity_type.enabled")%> data-off=<%= I18n.t("buttons.engagement_by_activity_type.disabled")%> >
            </div>
            <span id='engagement-by-activity-type' class="elearn-chart"></span>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if @courses.present? %>
    <div class="col-xs-12 col-sm-12 col-lg-6">
      <% @courses.each do |c| %>
        <div class="course-container well clearfix">
          <h4><%= c.full_name %></h4>
          <div class="course-details">
            <table class="table text-left borderless">
              <tr>
                <th>
                  <%= I18n.t('courses.lms') %>:
                </th>
                <td>
                  <%= link_to c.learning_management_system.name, c.learning_management_system.root, target: :_blank %>
                </td>
              </tr>
              <tr>
                <th>
                  <%= I18n.t('courses.normal_duration') %>:
                </th>
                <td>
                  <%= c.duration.to_s + ' ' + I18n.t('week').pluralize(c.duration) %>
                </td>
              </tr>
            </table>
          </div>
          
          <div class="btn-group pull-right">
            <%= link_to(course_engagement_performance_path(c.id), class: "btn btn-primary") do %>
              <span class="fa fa-bar-chart"></span> <%= I18n.t('courses.watch_progress') %>
            <% end %>

            <%= link_to(course_delete_enrollments_path(c), class: "btn btn-danger", data: { toggle: "tooltip", placement: "top", confirm: I18n.t('courses.alert_delete') }, title: I18n.t("courses.delete"), method: :post) do %>
              <span class="fa fa-times"></span>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>
    <% else %>
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="well" style="background: white; border-radius: 3px; border-color: #d4e3e8 !important; margin-top:100px; text-align:center;">
        <h4><%= raw I18n.t("courses.no_course_registered") %></h4>
      </div>
    </div>
    <% end %>
  </div>
</div>