config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  get 'languages/change_language'

  
  
  get 'sing_in_by_token' => 'courses#sing_in_by_token'
  
  resources :languages do
    get 'change_language/:language' => 'languages#change_language'
  end
  
  resources :courses do
    post 'delete_enrollments' => 'enrollments#destroy_course_enrollments'
    get 'engagement_performance'
    get 'effectiveness_efficiency'
    get 'get_enrolled_weeks'
    get 'day_of_course'

    get 'engagement_performance_data' => 'dashboard#engagement_performance_data'
    get 'effectiveness_efficiency_data' => 'dashboard#effectiveness_efficiency_data'

    get 'progress_and_course_time_use' => 'dashboard#progress_and_course_time_use'
    get 'required_activities' => 'dashboard#required_activities'
  end

  resources :dashboard, only: :index do
    get 'sing_in_by_token', on: :collection
  end

  resources :notes do
  end

  get 'download_notes' => 'notes#download', :as => 'download_notes'

  get 'dashboard/effectiveness_data', :defaults => { :format => 'json' }
  get 'dashboard/activities_complete_data', :defaults => { :format => 'json' }

  resources :goals, only: [:index,:create] do
    get 'change_week',on: :collection
  end


  namespace :api, :defaults => { :format => 'json' } do
    post 'sign_up' => 'user_authentication#register_user'
    post 'auth_user' => 'user_authentication#authenticate_user'
    get 'validate_token' => 'user_authentication#validate_token'
    get 'urls' => 'url_receiver#index'
    post 'urls' => 'url_receiver#save_visited_url'

    #TODO: Create namespace for notes
    post 'create_note' => 'note#save_note'
    post 'get_note' => 'note#get_note'
    get 'notes' => 'note#notes'
    get 'courses' => 'courses#index'

    post 'get_effective_time' => 'charts#get_effective_time'

    namespace :sessions do
      post 'start', method: :start
      post 'get_current', method: :get_current
      post 'close', method: :close
    end

    namespace :user_profile do
      get 'details', method: :user_details
      post 'edit', method: :edit
      post 'destroy', method: :destroy
    end

  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/goal.rb
class Goal < ApplicationRecord

  belongs_to :enrollment
  has_many :goal_details, dependent: :destroy
  has_one :goal_kpi_group, dependent: :destroy

  accepts_nested_attributes_for :goal_kpi_group

  validates_numericality_of :goal_hours
  validates_numericality_of :goal_evaluations
  validates_numericality_of :goal_videos

  attr_accessor :details
  attr_accessor :working_days

  include PerformanceCalculations::ResourcesActivities

  def build_goal_details
    self.details = []
    kind_of_goal = GoalDetail::KINDS.keys[0]
    7.times do |index|
      new_date = self.start + index.days
      details.push(GoalDetail.new(kind:kind_of_goal.to_s,schedule_date:new_date))
    end

  end

  def create_goal_details(picked_dates)
    kind_of_goal = GoalDetail::KINDS.keys[0]

    7.times do |index|
      new_date = self.start + index.day
      picked = picked_dates.include?(new_date.strftime("%Y-%m-%d"))
      
      GoalDetail.create(
                    goal_id:self.id,
                    kind:kind_of_goal.to_s,
                    schedule_date:new_date,
                    picked:picked
                    )
    end
  end

  def create_kpi_group
    enrollment = self.enrollment
    week = self.week

    avg_completers_kpis = enrollment.avg_completers(week-1)

    GoalKpiGroup.create(
      goal: self,

      videos_last_week: enrollment.videos_watched(week),
      evals_last_week: enrollment.exams_done(week),
      
      most_effective_day: enrollment.most_effective_day,
      
      avg_weekly_videos: enrollment.avg_videos_watched.round(1),
      avg_weekly_exams: enrollment.avg_exams_done.round(1),
      avg_weekly_time: enrollment.avg_time_invested_per_week.round(1),
      avg_weekly_time_videos: enrollment.avg_time_invested_per_week(Resource::CATEGORIES[:lectures]).round(1),
      avg_weekly_time_exams: enrollment.avg_time_invested_per_week(Resource::CATEGORIES[:evaluations]).round(1),
      
      total_videos_this_week: enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:lectures], module: week-1).distinct.count,
      total_evals_this_week: enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:evaluations], module: week-1).distinct.count,
      total_time_videos_week: enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:lectures], module: week-1).distinct.sum(:duration),
      total_time_evals_week: enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:evaluations], module: week-1).distinct.sum(:duration),
      
      avg_videos_completers: avg_completers_kpis[0].round(1),
      avg_evals_completers: avg_completers_kpis[1].round(1),
      avg_time_completers: avg_completers_kpis[2].round(1)
    )
  end

  def self.create_or_initialize_by_params(user, enrollment,week)
    start_goal_date = enrollment.date_enrolled.beginning_of_day + (week-1).week
    end_goal_date = start_goal_date + 6.day
    goal = Goal.find_or_initialize_by(
      user_id: user.id,
      enrollment_id: enrollment.id,
      week: week,
      start: start_goal_date,
      finish:end_goal_date
    )

    goal
  end

  def self.create_by_params(params)
    enrollment = Enrollment.find(params[:enrollment_id])

    start_date = enrollment.date_enrolled.beginning_of_day + (params[:week].to_i - 1).week
    end_date = start_date + 6.days
    @goal = Goal.new(
      user_id:params[:user_id],
      start:start_date,
      finish:end_date,
      goal_hours:params[:goal_hours],
      goal_videos:params[:goal_videos],
      goal_evaluations:params[:goal_evaluations],
      week:params[:week],
      enrollment_id:enrollment.id
    )

    result = @goal.save
    @goal.create_goal_details(params[:working_days].keys) if result
    @goal.create_kpi_group if result

    @goal
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  #before_action :set_goal, only: [:show, :edit, :update, :destroy]
  #before_action :set_parameters, only: [:index]

  # GET /goals
  # GET /goals.json
  def index
    @courses = current_user.courses
    @course ||= @courses.first

    if @course.present?

      @weeks = @course.weeks
      
      @enrollment = Enrollment.joins(edition: :course).where(courses:{id: @course.id},user_id:current_user.id).first
      @current_week = @enrollment.current_week
      @goal = Goal.create_or_initialize_by_params(current_user,@enrollment,@current_week)
      @goal.build_goal_details unless @goal.persisted?
      
      if @goal.persisted?
        set_charts_data
      else
        set_kpis(@enrollment, @current_week)
      end
    end

  end


  def change_week
    @course = Course.find(params[:course_id])
    @enrollment = Enrollment.joins(edition: :course).where(courses:{id: @course.id},user_id:current_user.id).first
    @current_week  = params[:week].to_i

    @goal = Goal.create_or_initialize_by_params(current_user,@enrollment,@current_week)
    @goal.build_goal_details unless @goal.persisted?
    
    set_kpis(@enrollment, @current_week)

    if @goal.persisted?
      set_charts_data
    end

    respond_to do |format|
      format.js {}
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.create_by_params(goal_params.merge({user_id:current_user.id}))

    respond_to do |format|
      if @goal.persisted?
        set_goal_elements
        set_charts_data
        format.js{}
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal)
    end

    def set_goal_elements
      @enrollment = @goal.enrollment
      @course = @enrollment.edition.course
      @current_week = @enrollment.current_week
    end

    def set_charts_data
      @activities_chart_data = [
        { 'label': 'Videos', 'values': [@enrollment.videos_watched(@current_week), @goal.goal_videos] },
        { 'label': 'Evaluations', 'values': [@enrollment.exams_done(@current_week), @goal.goal_evaluations]}
      ]
      @time_chart_data = [{ label: 'Time invested', values: [@enrollment.time_invested(@current_week)/(60.0*60.0), @goal.goal_hours] }]

    end

    def set_kpis(enrollment, week)
      videos_watched = enrollment.videos_watched(week)
      exams_done = enrollment.exams_done(week)
      avg_videos = enrollment.avg_videos_watched.round(1)
      avg_exams = enrollment.avg_exams_done.round(1)
      avg_time_week = (enrollment.avg_time_invested_per_week/60.0).round(1)
      avg_time_exam = (enrollment.avg_time_invested_per_week(Resource::CATEGORIES[:evaluations])/60.0).round(1)
      avg_time_videos = (enrollment.avg_time_invested_per_week(Resource::CATEGORIES[:lectures])/60.0).round(1)

      most_effective_day = enrollment.most_effective_day
      
      total_videos_this_week = enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:lectures], module: week-1).distinct.count
      total_evals_this_week = enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:evaluations], module: week-1).distinct.count
      total_time_videos_week = enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:lectures], module: week-1).distinct.sum(:duration)
      total_time_evals_week = enrollment.edition.course.resources.where(category: Resource::CATEGORIES[:evaluations], module: week-1).distinct.sum(:duration)

      avg_completers_kpis = enrollment.avg_completers(week-1)
      
      avg_videos_completers = avg_completers_kpis[0].round(1)
      avg_evals_completers = avg_completers_kpis[1].round(1)
      avg_time_completers = avg_completers_kpis[2].round(1)

      @categorized_kpis = [
        { category: I18n.t("goals.categories.course_performance_previous_week"),
          kpis: [
            { value: videos_watched, msg: I18n.t("goals.statistics.videos_last_week")},
            { value: exams_done, msg: I18n.t("goals.statistics.exams_last_week")}
          ]
        },
        { category: I18n.t("goals.categories.course_performance"),
          kpis: [
            { value: most_effective_day, msg: I18n.t("goals.statistics.most_effective_day")},
            { value: avg_videos, msg: I18n.t("goals.statistics.avg_weekly_videos")},
            { value: avg_exams, msg: I18n.t("goals.statistics.avg_weekly_exams")},
            { value: avg_time_week.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.avg_weekly_time")},
            { value: avg_time_exam.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.avg_weekly_time_exams")},
            { value: avg_time_videos.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.avg_weekly_time_videos")},
          ]
        },
        { category: I18n.t("goals.categories.activities_this_week"),
          kpis: [
            { value: total_videos_this_week, msg: I18n.t("goals.statistics.this_week_videos")},
            { value: total_evals_this_week, msg: I18n.t("goals.statistics.this_week_exams")},
            { value: total_time_videos_week.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.this_week_videos_time")},
            { value: total_time_evals_week.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.this_week_exams_time")},
          ]
        },
        { category: I18n.t("goals.categories.other_students_performance"),
          kpis: [
            { value: avg_videos_completers, msg: I18n.t("goals.statistics.avg_videos_completers")},
            { value: avg_evals_completers, msg: I18n.t("goals.statistics.avg_exams_completers")},
            { value: avg_time_completers.to_s + " " + I18n.t('graphs.dataUnit.min'), msg: I18n.t("goals.statistics.avg_time_completers")}
          ]
        }
      ]
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_define_goals.html.erb
<% unless goal.persisted? %>
  <div class="row">
    <%= render partial:"goals/form" , locals: { goal: goal, course_id: course_id, enrollment_id: enrollment_id,week: week} %>
  </div>
<% else%>
  <%= render partial: "goals/goal", locals:{goal:goal} %>
<% end %>

app/views/goals/_form.html.erb
<%= form_for goal, url: goals_path, html: { method: :post }, remote: true do |form| %>
  <%= form.hidden_field :enrollment_id, value: enrollment_id %>
  <%= form.hidden_field :week, value: week %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-12 padding-0">
    <h4 class="section-title"><%= I18n.t('goals.sections.form') %></h4>
    <hr class="section-title-underline">
  </div>

  <div class="col-xs-12 col-lg-6 padding-0">
    <div class="well chart-container">
      <div class="form-group">
        <label><%= I18n.t("goals.form.define_days",week: week) %></label>
      </div>

      <ul class="list-unstyled" style="margin-left:30px;">
        <% if !goal.details.nil? %>
          <% goal.details.each_with_index do |detail, index| %>
              <li class="">
                <%if index == 0 %>
                  <%= check_box_tag "goal[working_days][#{detail.formated_schedule_date}]", false, data:{validation:"checkbox_group required","validation-qty" => "min1" } %>
                <% else %>
                    <%= check_box_tag "goal[working_days][#{detail.formated_schedule_date}]"%>
                <% end %>
                <%= label_tag "goal[working_days][#{detail.formated_schedule_date}]", detail.title %>
              </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-xs-12 col-lg-6 padding-0">
    <div class="well chart-container">

      <div class="form-group">
        <label><%= I18n.t("goals.form.define_objectives", week: week) %> </label>
      </div>

      <div style="margin-left: 30px;">
        <div class="form-group">
          <%= form.label :goal_hours, "#{I18n.t("goals.form.goal_hours")}" %>
          <%= form.number_field :goal_hours, min:0, max: 70, class: "form-control",  placeholder: "#{I18n.t("goals.form.define_hours")}", data:{validation:"required"}  %>
        </div>

        <div class="form-group">
          <%= form.label :goal_videos, "#{I18n.t("goals.form.goal_videos")}" %>
          <%= form.number_field :goal_videos, min:0, max: 50, class: "form-control", placeholder: "#{I18n.t("goals.form.define_videos")}", data:{validation:"required"}  %>
        </div>

        <div class="form-group">
          <%= form.label :goal_evaluations, "#{I18n.t("goals.form.goal_evaluations")}" %>
          <%= form.number_field :goal_evaluations, min: 0, max: 40, class: "form-control", placeholder: "#{I18n.t("goals.form.define_evaluations")}" , data:{validation:"required"} %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions pull-right">
    <%= form.submit "#{I18n.t("goals.buttons.define_goals")}", class: "btn btn-primary analytics-click-defineGoal", 'data-course-id': course_id %>
  </div>

  <%= render partial:"goals/statistics" , locals: { categorized_kpis: @categorized_kpis} %>
</div>

<% end %>


<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script>
    $.validate();
</script>

app/views/goals/_goal.html.erb
<div class="well chart-container" style="min-height:100px !important;" >
  <h3 class="chart-title"> <%= I18n.t('goals.titles.activities_goals') %> </h3>
  <span id="activities-goal-chart" class="elearn-chart"></span>
</div>

<div class="well chart-container" style="min-height:100px !important;" >
  <h3 class="chart-title"> <%= I18n.t('goals.titles.time_goals') %> </h3>
  <span id="time-goal-chart" class="elearn-chart"></span>
</div>

app/views/goals/_statistics.html.erb
<div class="col-xs-12 padding-0">
  <h4 class="section-title"><%= I18n.t('goals.sections.kpis') %></h4>
  <hr class="section-title-underline">
  <div class="well chart-container">
    <% categorized_kpis.each_with_index do |category, index| %>
      <label><%= category[:category] %></label>
      <table class="table table-hover">
        <tbody>
          <% category[:kpis].each do |kpi| %>
            <tr>
              <td colspan="2"><%= kpi[:msg] %></td>
              <th scope="row" class="text-right" style="white-space: nowrap;"><h4><%= kpi[:value] %></h4></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

app/views/goals/change_week.js.erb
message_container = $('#notice');
message_container.empty();
message_container.html('<%= escape_javascript( render 'layouts/messages') %>');


var persisted = <%= @goal.persisted? %>;
$('#goals-container').empty();

if(persisted)
{
  $('#goals-container').html('<%= escape_javascript(render partial: "goals/goal", locals:{ goal: @goal } ) %>');
  //console.log(<%= raw @activities_chart_data.to_json %>);
  drawGoalsChart('#activities-goal-chart', 160, <%= raw @activities_chart_data.to_json %>, 'activities');
  drawGoalsChart('#time-goal-chart', 100, <%= raw @time_chart_data.to_json %>, 'hrs');

}else{
  $('#goals-container').html('<%= escape_javascript(render partial: "goals/form", locals:{ goal: @goal, course_id: @course.id, enrollment_id: @enrollment.id, week: @current_week} ) %>');
}

app/views/goals/create.js.erb
$('#goals-container').empty();
$('#goals-container').html('<%= escape_javascript(render partial: "goals/goal", locals:{ goal: @goal } ) %>');

drawGoalsChart('#activities-goal-chart', 160, <%= raw @activities_chart_data.to_json %>, 'activities');
drawGoalsChart('#time-goal-chart', 100, <%= raw @time_chart_data.to_json %>, 'hrs');

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<% if @course.present? and @enrollment.present? %>
<div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 padding-0">
  <div class="row">
    <div class="col-xs-7 col-md-9 col-lg-5">
      <div class="form-group">
        <label><%= I18n.t("goals.course") %></label>
        <%= select_tag "course", options_from_collection_for_select(@courses, "id", "full_name", @course), class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-5 col-md-3 col-lg-2">
      <div class="form-group">
        <label for="exampleInputPassword1"><%= I18n.t("goals.week") %></label>
        <%= select_tag "week", options_from_collection_for_select(@weeks, "week", "title", @current_week), class: "form-control week"  %>
      </div>
    </div>
  </div>

  <div id="goals-container">
    <% unless @goal.persisted? %>
    <%= render partial:"goals/form" , locals: { goal: @goal, course_id: @course.id, enrollment_id: @enrollment.id, week: @current_week } %>
    <% else %>
    <%= render partial: "goals/goal", locals: { goal: @goal, activities_chart_data: @activities_chart_data, time_chart_data: @time_chart_data } %>
    <% end %>
  </div>
</div>

<%else %>
<div class="col-xs-12 col-md-6 col-md-offset-3">
  <div class="well" style="background: white; border-radius: 3px; border-color: #d4e3e8 !important; margin-top:100px; text-align:center;">
    <h4><%= I18n.t("courses.no_course_registered").html_safe %></h4>
    <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>