config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  get 'languages/change_language'

  
  
  get 'sing_in_by_token' => 'courses#sing_in_by_token'
  
  resources :languages do
    get 'change_language/:language' => 'languages#change_language'
  end
  
  resources :courses do
    post 'delete_enrollments' => 'enrollments#destroy_course_enrollments'
    get 'engagement_performance'
    get 'effectiveness_efficiency'
    get 'get_enrolled_weeks'
    get 'day_of_course'

    get 'engagement_performance_data' => 'dashboard#engagement_performance_data'
    get 'effectiveness_efficiency_data' => 'dashboard#effectiveness_efficiency_data'

    get 'progress_and_course_time_use' => 'dashboard#progress_and_course_time_use'
    get 'required_activities' => 'dashboard#required_activities'
  end

  resources :dashboard, only: :index do
    get 'sing_in_by_token', on: :collection
  end

  resources :notes do
  end

  get 'download_notes' => 'notes#download', :as => 'download_notes'

  get 'dashboard/effectiveness_data', :defaults => { :format => 'json' }
  get 'dashboard/activities_complete_data', :defaults => { :format => 'json' }

  resources :goals, only: [:index,:create] do
    get 'change_week',on: :collection
  end


  namespace :api, :defaults => { :format => 'json' } do
    post 'sign_up' => 'user_authentication#register_user'
    post 'auth_user' => 'user_authentication#authenticate_user'
    get 'validate_token' => 'user_authentication#validate_token'
    get 'urls' => 'url_receiver#index'
    post 'urls' => 'url_receiver#save_visited_url'

    #TODO: Create namespace for notes
    post 'create_note' => 'note#save_note'
    post 'get_note' => 'note#get_note'
    get 'notes' => 'note#notes'
    get 'courses' => 'courses#index'

    post 'get_effective_time' => 'charts#get_effective_time'

    namespace :sessions do
      post 'start', method: :start
      post 'get_current', method: :get_current
      post 'close', method: :close
    end

    namespace :user_profile do
      get 'details', method: :user_details
      post 'edit', method: :edit
      post 'destroy', method: :destroy
    end

  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="col-xs-3 pull-right alert alert-dismissible alert-<%= name.to_s %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">


        <div class="col-xs-2"></div>
        <div class="page-title">
          <span><%= view_title %></span>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t('languages.language') %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%= language_select %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to I18n.t('login.log_out'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_sidebar.erb
<div class="side-bar-logo"></div>

<ul class="nav nav-sidebar" id="main-sidebar">
  <div class="<%= "active" if params[:controller] == "courses" %> sidebar-item courses-menu-option">
    <li class="analytics-click-coursesMenuOpt"><%= link_to courses_path do %><i class="fa fa-bars"></i> <%= I18n.t("sidebar.My courses") %><% end %></li>
    <div id="courses-menu">
      <ul class="nav nav-sidebar sidebar-items-container">
        <% Course.from_user(current_user).each do |course| %>
        <li class="sidebar-item analytics-click-coursesMenuOpt">
          <%= link_to course_engagement_performance_path(course.id) do %><i class="fa fa-book"></i> <%= truncate(course.full_name, length: 40, separator: ' ') %><% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <li class="<%= "active" if params[:controller] == "notes" %> sidebar-item analytics-click-notesMenuOpt"><%= link_to notes_path do %><i class="fa fa-sticky-note" aria-hidden="true"></i> <%= I18n.t("sidebar.My notes") %> <% end %></li>
  <li class="<%= "active" if params[:controller] == "goals" %> sidebar-item analytics-click-goalsMenuOpt"><%= link_to goals_path do %><i class="fa fa-dot-circle-o" aria-hidden="true"></i> <%= I18n.t("sidebar.My goals") %><% end %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MyNoteProgress" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chrome Extension Dashboard Api" %>">
  <%= favicon_link_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
  <script type="text/javascript">
    I18n.defaultLocale = "<%= I18n.default_locale %>";
    I18n.locale = "<%= I18n.locale %>";
  </script>
</head>

<body>
  <%= render 'layouts/messages' %>

  <% if user_signed_in? %>
  <%= render 'layouts/navigation' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/sidebar' %>
      </div>
      <div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>
  </div>
  <% else %>
  <%= render 'layouts/messages' %>
  <%= yield %>
  <% end %>
</body>
</html>